### ISSUE TITLE
vim color scheme error

### ISSUE THREAD

**Issue by harris21** [daylerees/colour-schemes#142]
Hello there.
I am trying to apply a vim color scheme.
The problem is, I cannot make it work, although it works fine in MacVim.
I have attached two images, one using macvim and one using terminal vim.
I've been searching for over 5 hours and this thing is driving me crazy. 
Any ideas what am I doing wrong??
![screen shot 2014-03-28 at 3 47 58 am](https://cloud.githubusercontent.com/assets/1542015/2545585/57c8e5d4-b61b-11e3-91ff-61b1fcc95acf.png)
![screen shot 2014-03-28 at 3 49 32 am](https://cloud.githubusercontent.com/assets/1542015/2545586/57cb91ee-b61b-11e3-9da3-640fffe42312.png)

**Comment by rrotaru** [comment]
Here's a link to a [really simple python script](https://gist.github.com/MicahElliott/719710) that can generate the closest color in a 256 color palette based on the hex code.
I was super happy with Snappy for MacVim but noticed that it sucks in terminal, so I went in and edited the colorscheme file to fix it and it turned out fairly well. Check out the before and after as well as the file itself.
![Before](http://i.imgur.com/kuzajDc.png) ![After](http://i.imgur.com/LfmSCdJ.png)
https://gist.github.com/rrotaru/869f85fa860271c1d11f

@daylerees if you're interested and you like the way Snappy turned out, I can help convert the rest of your colorschemes and send you a pull request with the changes

**Comment by thomasbkahn** [comment]
@rrotaru I'm interested. If there hasn't been any response would you consider making a fork?

**Comment by rrotaru** [comment]
Done @thomasbkahn. Here's [the fork](https://github.com/rrotaru/colour-schemes), and the [pull request](https://github.com/daylerees/colour-schemes/pull/204).

Thanks for reminding me about this, I meant to get back to finishing it a while ago.

**Comment by thomasbkahn** [comment]
@rrotaru Awesome, thanks!

**Comment by rrotaru** [comment]
For the sake of posterity for anyone who stumbles across this and wants to convert future colorschemes, here is the python script I wrote to convert the color codes from hex to 256 term values for these files:
https://gist.github.com/rrotaru/4911151e3623f2af7e9f8ade58ccf33d

You will also need this file to run this successfully:
https://gist.github.com/MicahElliott/719710

Ping @daylerees
